### ISSUE TITLE
Редактирование сообщений

### ISSUE THREAD

**Issue by gdesra4** [aeremin/larp-bugle-telegram-bot#10]
Я, как модератор канала, хочу отредактировать сообщение перед отправкой в канал — например, поправить ошибки.

**Comment by aeremin** [comment]
Вопрос как это сделать. Телеграм не позволяет редактировать чужие сообщения (единственное исключение - админ канала может редактировать сообщения канала, даже запощенные другими админами). Делать отдельный веб-интерфейс - не хочется. Вариант "скопировали сообщение, поправили, запостили обратно" - неудобный (и его и сейчас ничего не мешает использовать - копируем из модерского чата, постим в чат с ботом).

Другие идеи?

**Comment by gdesra4** [comment]
Нет :-(
